### ISSUE TITLE
some unit types cannot be placed in the editor

### ISSUE THREAD

**Issue by ttinies** [ttinies/sc2simulator#17]
example:  hellion -> hellbat transformation cannot occur without an armory present on the map.

Currently, an armory is not available to be placed on the map.

**Comment by ttinies** [comment]
per discussion, it may end up being best just to enable the placement of all buildings for each race and allow the scenario builder to meet tech requirements as they desire.

**Comment by TheWisp** [comment]
All 3 race buildings implemented
